"""Generate the attacker entity files from one roster.

    python tools/gen_entities.py

Writes packs/BP/entities/<name>.json and packs/RP/entity/<name>.entity.json
for every mob in ROSTER. The generated files are committed; edit this script,
not them. dm:core is hand-written.

Client entities use the plain 1.8/1.10 vanilla formats with the default
render controller. The 1.26 zombie client file (spear and kinetic weapon
queries) renders custom entities invisible.
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BP = ROOT / "packs/BP/entities"
RP = ROOT / "packs/RP/entity"
GEN_NOTE = "Generated by tools/gen_entities.py; edit that instead."

# ---------------------------------------------------------------- roster

ROSTER = {
    "zombie": {
        "base": "zombie", "name": "Siege Zombie", "health": 20, "speed": 0.23, "attack": 3,
        "texture": "textures/entity/zombie/zombie", "families": ["zombie", "undead"],
    },
    "swarmer": {
        "base": "zombie", "name": "Swarmer", "health": 14, "speed": 0.27, "attack": 2,
        "texture": "textures/entity/zombie/husk", "families": ["zombie", "undead"], "scale": 0.9,
    },
    "digger": {
        "base": "zombie", "name": "Digger", "health": 26, "speed": 0.21, "attack": 3,
        "texture": "textures/entity/zombie/zombie", "families": ["zombie", "undead"],
        "equipment": "loot_tables/dm/digger_gear.json",
    },
    "skeleton": {
        "base": "skeleton", "name": "Siege Skeleton", "health": 20, "speed": 0.25,
        "texture": "textures/entity/skeleton/skeleton", "families": ["skeleton", "undead"],
    },
    "siege_skeleton": {
        "base": "skeleton", "name": "Siege Archer", "health": 20, "speed": 0.25,
        "texture": "textures/entity/skeleton/stray", "families": ["skeleton", "undead"],
    },
    "sapper": {
        "base": "creeper", "name": "Sapper", "health": 20, "speed": 0.22,
        "families": ["creeper"], "power": 3, "template": "creeper",
    },
    # Flyers: no breach modules; they bypass walls and attack from the air.
    "ghast": {
        "base": "ghast", "name": "Siege Ghast", "health": 20, "speed": 0.06,
        "families": ["ghast", "dm_flyer"], "template": "ghast", "runtime": True, "targeting": "core_only",
    },
    "blaze": {
        "base": "blaze", "name": "Blaze", "health": 20, "speed": 0.23,
        "families": ["blaze", "dm_flyer"], "template": "blaze", "runtime": True,
    },
    "phantom": {
        "base": "phantom", "name": "Phantom", "health": 20, "speed": 1.8, "attack": 6,
        "families": ["phantom", "undead", "dm_flyer"], "template": "phantom",
    },
}
# Tower guards: defense mode (scripts/tower.js).
ROSTER.update({
    "guard_zombie": {
        "base": "zombie", "name": "Tower Guard", "health": 24, "speed": 0.23, "attack": 4, "guard": True,
        "texture": "textures/entity/zombie/zombie", "families": ["zombie", "undead"],
        "equipment": "loot_tables/dm/guard_gear.json",
    },
    "guard_archer": {
        "base": "skeleton", "name": "Tower Archer", "health": 20, "speed": 0.25, "guard": True,
        "texture": "textures/entity/skeleton/wither_skeleton", "families": ["skeleton", "undead"],
    },
    "guard_captain": {
        "base": "zombie", "name": "Tower Captain", "health": 80, "speed": 0.2, "attack": 8, "guard": True,
        "texture": "textures/entity/zombie/husk", "families": ["zombie", "undead"], "scale": 1.5,
        "equipment": "loot_tables/dm/captain_gear.json",
    },
})

# Bosses: big, tough, a boss bar, knockback-resistant. Any wave group or DM
# spawn can include them; scripts announce them (roster.js `boss`).
ROSTER.update({
    "warlord": {
        "base": "zombie", "name": "Warlord", "health": 400, "speed": 0.21, "attack": 12, "boss": True,
        "texture": "textures/entity/zombie/zombie", "families": ["zombie", "undead"], "scale": 2.4,
        "collision": (1.4, 4.4), "equipment": "loot_tables/dm/warlord_gear.json",
    },
    "colossus": {
        "base": "skeleton", "name": "Bone Colossus", "health": 300, "speed": 0.22, "boss": True,
        "texture": "textures/entity/skeleton/stray", "families": ["skeleton", "undead"], "scale": 2.2,
        "collision": (1.3, 4.2), "ranged": {"interval": 1.2, "range": 28},
    },
    "necromancer": {
        "base": "skeleton", "name": "Necromancer", "health": 200, "speed": 0.24, "boss": True,
        "texture": "textures/entity/skeleton/wither_skeleton", "families": ["skeleton", "undead"], "scale": 1.4,
        "collision": (0.8, 2.7), "ranged": {"interval": 2.5, "range": 20},
    },
    "demolisher": {
        "base": "creeper", "name": "Demolisher", "health": 150, "speed": 0.18, "boss": True,
        "families": ["creeper"], "power": 7, "template": "creeper", "scale": 2.0, "collision": (1.2, 3.4),
    },
    "dread_ghast": {
        "base": "ghast", "name": "Dread Ghast", "health": 250, "speed": 0.06, "boss": True,
        "families": ["ghast", "dm_flyer"], "template": "ghast", "runtime": True, "targeting": "core_only",
        "scale": 1.5, "collision": (6.0, 6.0),
    },
})

FLYERS = ("ghast", "blaze", "phantom")
# Walking parts of common_components() a flyer doesn't get.
WALKING = (
    "minecraft:navigation.walk", "minecraft:movement.basic", "minecraft:jump.static",
    "minecraft:can_climb", "minecraft:behavior.random_stroll", "minecraft:pushable_by_block",
)

# ---------------------------------------------------------------- behavior


def target_entry(family, max_dist, must_see, priority=None):
    entry = {
        "filters": {"test": "is_family", "subject": "other", "value": family},
        "max_dist": max_dist,
        "must_see": must_see,
    }
    if priority is not None:
        entry["priority"] = priority
    return entry


def targeting_groups(flyer=False):
    common = {"priority": 2, "must_see": False, "reselect_targets": True, "within_radius": 64}
    if flyer:
        # Flyers sit well above the core; without this they never pick it up.
        common["target_search_height"] = 80
    return {
        # Core only; ignores players unless hurt by one.
        "dm:tgt_core_only": {
            "minecraft:behavior.nearest_attackable_target": {
                **common, "entity_types": [target_entry("dm_core", 64, False)],
            }
        },
        # Core first, players inside the aggro radius second.
        "dm:tgt_prioritized": {
            "minecraft:behavior.nearest_prioritized_attackable_target": {
                **common,
                "entity_types": [
                    target_entry("dm_core", 64, False, 0),
                    # Turrets close by are fair game (players can lose them).
                    target_entry("dm_turret", 8, True, 1),
                    target_entry("player", 6, True, 2),
                ],
            }
        },
        # Whichever valid target is nearest.
        "dm:tgt_nearest": {
            "minecraft:behavior.nearest_attackable_target": {
                **common,
                "entity_types": [
                    target_entry("dm_core", 64, False),
                    target_entry("dm_turret", 8, True),
                    target_entry("player", 6, True),
                ],
            }
        },
    }


def targeting_events():
    names = ["dm:tgt_core_only", "dm:tgt_prioritized", "dm:tgt_nearest"]
    return {
        name: {
            "remove": {"component_groups": [n for n in names if n != name]},
            "add": {"component_groups": [name]},
        }
        for name in names
    }


def common_components(mob):
    return {
        "minecraft:type_family": {
            "family": ["dm_guard" if mob.get("guard") else "dm_attacker", *mob["families"], "monster", "mob"]
        },
        "minecraft:health": {"value": mob["health"], "max": mob["health"]},
        "minecraft:movement": {"value": mob["speed"]},
        "minecraft:follow_range": {"value": 64, "max": 64},
        "minecraft:collision_box": {"width": 0.6, "height": 1.9},
        # Retaliate against players, never against fellow attackers or tower
        # guards (stray arrows otherwise start infighting).
        "minecraft:behavior.hurt_by_target": {
            "priority": 1,
            "entity_types": [{"filters": {"all_of": [
                {"test": "is_family", "subject": "other", "operator": "!=", "value": "dm_attacker"},
                {"test": "is_family", "subject": "other", "operator": "!=", "value": "dm_guard"},
            ]}}],
        },
        "minecraft:behavior.random_stroll": {"priority": 7, "speed_multiplier": 1},
        "minecraft:behavior.look_at_player": {"priority": 8, "look_distance": 6},
        "minecraft:behavior.random_look_around": {"priority": 9},
        "minecraft:breathable": {
            "total_supply": 15, "suffocate_time": 0, "breathes_air": True, "breathes_water": True,
        },
        "minecraft:can_climb": {},
        "minecraft:jump.static": {},
        "minecraft:movement.basic": {},
        "minecraft:navigation.walk": {"can_walk": True, "is_amphibious": True, "can_pass_doors": True},
        "minecraft:physics": {},
        "minecraft:pushable_by_entity": {},
        "minecraft:pushable_by_block": {},
        "minecraft:nameable": {},
        "minecraft:persistent": {},
        "minecraft:conditional_bandwidth_optimization": {},
        "minecraft:hurt_on_condition": {"damage_conditions": [
            {"cause": "lava", "damage_per_tick": 4, "filters": {"test": "in_lava"}},
        ]},
    }


def behavior(name, mob):
    components = common_components(mob)
    groups = targeting_groups(flyer=mob["base"] in FLYERS)
    default = mob.get("targeting", "prioritized")
    events = {"minecraft:entity_spawned": {"add": {"component_groups": [f"dm:tgt_{default}"]}}}
    events.update(targeting_events())
    if mob.get("guard"):
        # Defense mode: hold position, fight players who come near, ignore
        # the core. (scripts/tower.js leashes them to their post.)
        components.pop("minecraft:behavior.random_stroll", None)
        groups = {
            "dm:tgt_guard": {
                "minecraft:behavior.nearest_attackable_target": {
                    "priority": 2, "must_see": True, "reselect_targets": True, "within_radius": 16,
                    "entity_types": [target_entry("player", 16, True)],
                }
            }
        }
        events = {"minecraft:entity_spawned": {"add": {"component_groups": ["dm:tgt_guard"]}}}

    if mob["base"] == "zombie":
        components["minecraft:attack"] = {"damage": mob["attack"]}
        components["minecraft:behavior.melee_box_attack"] = {"priority": 4, "track_target": True}
    elif mob["base"] == "skeleton":
        components["minecraft:equipment"] = {"table": "loot_tables/entities/skeleton_gear.json"}
        components["minecraft:shooter"] = {"def": "minecraft:arrow", "sound": "bow"}
        components["minecraft:behavior.ranged_attack"] = {
            "priority": 0,
            "attack_interval": {"min": 3.0, "max": 3.0},
            "attack_range": {"min": 0.0, "max": 15.0},
        }
        components["minecraft:navigation.walk"]["avoid_water"] = True
    elif mob["base"] in FLYERS:
        for key in WALKING:
            components.pop(key, None)
        components["minecraft:can_fly"] = {}
        components["minecraft:fire_immune"] = {}
        flight = {
            # Floats slowly and shells the core from up to 64 blocks; its
            # fireballs explode and break blocks.
            "ghast": {
                "minecraft:collision_box": {"width": 4.0, "height": 4.0},
                "minecraft:physics": {},
                "minecraft:navigation.float": {"can_path_over_water": True},
                "minecraft:behavior.float": {"priority": 0},
                "minecraft:behavior.float_wander": {
                    # Vanilla wander drifts upward until the ghast is too high to
                    # fire at the core (tested); keep it low and close.
                    "priority": 3, "must_reach": True, "random_reselect": True, "float_duration": {"min": 2, "max": 7},
                    "xz_dist": 8, "y_dist": 3, "y_offset": -2,
                },
                "minecraft:behavior.ranged_attack": {
                    "priority": 1, "attack_range": {"min": 0.0, "max": 64.0},
                    "charge_charged_trigger": 1, "charge_shoot_trigger": 2,
                },
                "minecraft:shooter": {"def": "minecraft:fireball"},
            },
            # Fires bursts of small fireballs (from 18 blocks: further out it parks
            # and shoots into the hills between it and the core), which set wooden defenses
            # alight. Its flight comes from the vanilla blaze runtime, which
            # walks on vanilla's components, so it keeps them.
            "blaze": {
                "minecraft:collision_box": {"width": 0.5, "height": 1.8},
                "minecraft:physics": {},
                "minecraft:movement.basic": {},
                "minecraft:jump.static": {},
                "minecraft:navigation.walk": {"avoid_damage_blocks": True, "avoid_water": True, "can_path_over_water": True},
                "minecraft:behavior.float": {"priority": 0},
                "minecraft:behavior.ranged_attack": {
                    "priority": 3, "attack_interval": {"min": 3.0, "max": 5.0}, "attack_range": {"min": 0.0, "max": 18.0},
                    "charge_shoot_trigger": 4.0, "burst_shots": 3, "burst_interval": 0.3,
                },
                "minecraft:shooter": {"def": "minecraft:small_fireball"},
            },
            # Circles high above and swoops down on its target.
            "phantom": {
                "minecraft:collision_box": {"width": 0.9, "height": 0.5},
                "minecraft:physics": {"has_gravity": False},
                "minecraft:movement.glide": {"start_speed": 0.1, "speed_when_turning": 0.2},
                "minecraft:attack": {"damage": mob.get("attack", 6)},
                "minecraft:behavior.swoop_attack": {"priority": 2},
                "minecraft:behavior.circle_around_anchor": {
                    "priority": 3, "goal_radius": 1, "height_offset_range": {"min": -4, "max": 5},
                    "height_above_target_range": {"min": 10, "max": 20},
                },
            },
        }[mob["base"]]
        components.update(flight)
        if mob["base"] == "blaze":
            components.pop("minecraft:can_fly", None)
    elif mob["base"] == "creeper":
        components["minecraft:collision_box"] = {"width": 0.6, "height": 1.8}
        components["minecraft:attack"] = {"damage": 3}
        components["minecraft:behavior.melee_box_attack"] = {"priority": 4, "track_target": True}
        components["minecraft:behavior.swell"] = {"priority": 2, "start_distance": 2.5, "stop_distance": 6}
        components["minecraft:target_nearby_sensor"] = {
            "inside_range": 2.5,
            "outside_range": 6,
            "must_see": True,
            "on_inside_range": {"event": "minecraft:start_exploding", "target": "self"},
            "on_outside_range": {"event": "minecraft:stop_exploding", "target": "self"},
            "on_vision_lost_inside_range": {"event": "minecraft:stop_exploding", "target": "self"},
        }
        explode = {"fuse_length": 1.5, "fuse_lit": True, "power": mob["power"],
                   "causes_fire": False, "breaks_blocks": True, "destroy_affected_by_griefing": False}
        groups["dm:exploding"] = {"minecraft:explode": explode}
        # Scripts fire this when the sapper is stuck at a wall (detonate_stuck).
        groups["dm:detonating"] = {"minecraft:explode": explode}
        events["minecraft:start_exploding"] = {"add": {"component_groups": ["dm:exploding"]}}
        events["minecraft:stop_exploding"] = {"remove": {"component_groups": ["dm:exploding"]}}
        events["dm:detonate"] = {"add": {"component_groups": ["dm:detonating"]}}

    if mob.get("equipment"):
        components["minecraft:equipment"] = {
            "table": mob["equipment"],
            "slot_drop_chance": [
                {"slot": "slot.weapon.mainhand", "drop_chance": 0},
                {"slot": "slot.armor.head", "drop_chance": 0},
            ],
        }
    if mob.get("scale"):
        components["minecraft:scale"] = {"value": mob["scale"]}
    if mob.get("collision"):
        width, height = mob["collision"]
        components["minecraft:collision_box"] = {"width": width, "height": height}
    if mob.get("ranged") and "minecraft:behavior.ranged_attack" in components:
        ranged = mob["ranged"]
        components["minecraft:behavior.ranged_attack"].update({
            "attack_interval": {"min": ranged["interval"], "max": ranged["interval"]},
            "attack_range": {"min": 0.0, "max": float(ranged["range"])},
        })
    if mob.get("boss"):
        components["minecraft:type_family"]["family"].insert(1, "dm_boss")
        components["minecraft:boss"] = {"should_darken_sky": False, "hud_range": 64}
        components["minecraft:knockback_resistance"] = {"value": 0.9}

    return {
        "format_version": "1.26.50",
        "minecraft:entity": {
            "description": {
                "identifier": f"dm:{name}",
                "is_summonable": True,
                "is_spawnable": True,
                **({"runtime_identifier": f"minecraft:{mob['base']}"} if mob.get("runtime") else {}),
            },
            "components": components,
            "component_groups": groups,
            "events": events,
        },
    }


# ---------------------------------------------------------------- client

HUMANOID_SCRIPTS = {
    "pre_animation": [
        "variable.tcos0 = (Math.cos(query.modified_distance_moved * 38.17) * query.modified_move_speed / variable.gliding_speed_value) * 57.3;",
    ],
}

HUMANOID_ANIMATIONS = {
    "look_at_target_default": "animation.humanoid.look_at_target.default",
    "look_at_target_gliding": "animation.humanoid.look_at_target.gliding",
    "look_at_target_swimming": "animation.humanoid.look_at_target.swimming",
    "move": "animation.humanoid.move",
    "riding.arms": "animation.humanoid.riding.arms",
    "riding.legs": "animation.humanoid.riding.legs",
    "riding.body": "animation.humanoid.riding.body",
    "holding": "animation.humanoid.holding",
    "attack.rotations": "animation.humanoid.attack.rotations",
    "bob": "animation.humanoid.bob",
}
HUMANOID_CONTROLLERS = [
    {"look_at_target": "controller.animation.humanoid.look_at_target"},
    {"move": "controller.animation.humanoid.move"},
    {"riding": "controller.animation.humanoid.riding"},
    {"holding": "controller.animation.humanoid.holding"},
    {"attack": "controller.animation.humanoid.attack"},
    {"bob": "controller.animation.humanoid.bob"},
]


def client(name, mob):
    ident = f"dm:{name}"
    if mob.get("template"):
        # A Mojang client entity in the 1.8/1.10 format, renamed (tools/templates).
        data = json.loads((ROOT / f"tools/templates/{mob['template']}.entity.json").read_text(encoding="utf-8"))
        data["minecraft:client_entity"]["description"]["identifier"] = ident
        return data

    animations = dict(HUMANOID_ANIMATIONS)
    controllers = list(HUMANOID_CONTROLLERS)
    if mob["base"] == "zombie":
        geometry, material = "geometry.zombie.v1.8", "zombie"
        animations["zombie_attack_bare_hand"] = "animation.zombie.attack_bare_hand"
        controllers.append({"zombie_attack_bare_hand": "controller.animation.zombie.attack_bare_hand"})
        egg = "spawn_egg_zombie"
    else:
        geometry, material = "geometry.skeleton.v1.8", "skeleton"
        animations["bow_and_arrow"] = "animation.humanoid.bow_and_arrow"
        animations["skeleton_attack"] = "animation.skeleton.attack"
        controllers.append({"bow_and_arrow": "controller.animation.humanoid.bow_and_arrow"})
        controllers.append({"skeleton_attack": "controller.animation.skeleton.attack"})
        egg = "spawn_egg_skeleton"
    return {
        "format_version": "1.8.0",
        "minecraft:client_entity": {"description": {
            "identifier": ident,
            "min_engine_version": "1.8.0",
            "materials": {"default": material},
            "textures": {"default": mob["texture"]},
            "geometry": {"default": geometry},
            "scripts": HUMANOID_SCRIPTS,
            "animations": animations,
            "animation_controllers": controllers,
            "render_controllers": ["controller.render.default"],
            "enable_attachables": True,
            "spawn_egg": {"texture": egg},
        }},
    }


# ---------------------------------------------------------------- write


def write(path, data):
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def main():
    for name, mob in ROSTER.items():
        write(BP / f"{name}.json", behavior(name, mob))
        write(RP / f"{name}.entity.json", client(name, mob))
    write_defenses()
    lang = ROOT / "packs/RP/texts/en_US.lang"
    lines = [
        "pack.name=Defend the Core Resources",
        "pack.description=Client entities for Defend the Core",
        "entity.dm:core.name=Core",
    ]
    for name, mob in ROSTER.items():
        lines.append(f"entity.dm:{name}.name={mob['name']}")
        lines.append(f"item.spawn_egg.entity.dm:{name}.name=Spawn {mob['name']}")
    for name, turret in TURRETS.items():
        lines.append(f"entity.dm:{name}.name={turret['name']}")
    lines.append("entity.dm:vendor.name=Vendor")
    lines.append("action.interact.dtc_turret=Repair / Upgrade")
    lines.append("entity.dm:label.name=Label")
    for item_id, item in ITEMS.items():
        lines.append(f"item.dm:{item_id}={item['name']}")
    lang.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {len(ROSTER)} mobs; {GEN_NOTE}")


# ---------------------------------------------------------------- defenses

# Stationary turrets players buy and place. They target attackers only (the
# flak turret only flyers), can't be hurt by players, and attackers that
# come within 8 blocks fight them.
TURRETS = {
    "turret_arrow": {
        "name": "Arrow Turret", "health": 40, "range": 16, "interval": (1.5, 2.0), "burst": 2,
        "shoots": "minecraft:arrow", "targets": "dm_attacker", "template": "shulker",
    },
    "turret_flak": {
        # Phantoms are quick; a burst gives it a fair chance (tested: single
        # shots kept missing).
        "name": "Flak Turret", "health": 40, "range": 32, "interval": (1.0, 1.5), "burst": 3,
        "shoots": "minecraft:arrow", "targets": "dm_flyer", "template": "shulker",
    },
    "turret_frost": {
        "name": "Frost Turret", "health": 30, "range": 14, "interval": (1.0, 1.0),
        # Snowballs don't hurt; the script slows whatever they hit.
        "shoots": "minecraft:snowball", "targets": "dm_attacker", "template": "snow_golem",
    },
}

# Placeable defense items (used on a block; scripts/defenses.js does the
# placing) and the vanilla textures their icons borrow.
ITEMS = {
    "arrow_turret": {"name": "Arrow Turret", "icon": "textures/items/shulker_shell"},
    "flak_turret": {"name": "Flak Turret", "icon": "textures/items/shulker_shell"},
    "frost_turret": {"name": "Frost Turret", "icon": "textures/items/snowball"},
    "blast_mine": {"name": "Blast Mine", "icon": "textures/blocks/tnt_side"},
    "frost_mine": {"name": "Frost Mine", "icon": "textures/blocks/ice"},
}

# Players can't hurt defenses or the vendor; turrets don't hurt each other.
NO_PLAYER_DAMAGE = {
    "any_of": [
        {"test": "is_family", "subject": "other", "value": "player"},
        {"test": "is_family", "subject": "damager", "value": "player"},
        {"test": "is_family", "subject": "other", "value": "dm_turret"},
        {"test": "is_family", "subject": "damager", "value": "dm_turret"},
    ]
}


# Upgrade tiers (scripts/defenses.js triggers dtc:tier_N): longer reach,
# faster fire, bigger bursts. Health is set by the script (tier and the
# owner's Engineering), within MAX_TURRET_HEALTH.
TIERS = {1: (1.0, 1.0, 0), 2: (1.25, 0.75, 1), 3: (1.5, 0.55, 2)}  # range, interval, extra burst
MAX_TURRET_HEALTH = 400


def turret_tier(spec, tier):
    range_mult, interval_mult, extra = TIERS[tier]
    reach = round(spec["range"] * range_mult)
    burst = spec.get("burst", 1) + extra
    lo, hi = spec["interval"]
    return {
        "minecraft:behavior.nearest_attackable_target": {
            "priority": 1,
            "must_see": True,
            "reselect_targets": True,
            "within_radius": reach,
            "target_search_height": 64,
            "entity_types": [target_entry(spec["targets"], reach, True)],
        },
        "minecraft:behavior.ranged_attack": {
            "priority": 0,
            "attack_interval": {"min": round(lo * interval_mult, 2), "max": round(hi * interval_mult, 2)},
            "attack_range": {"min": 0.0, "max": float(reach)},
            **({"burst_shots": burst, "burst_interval": 0.2} if burst > 1 else {}),
        },
    }


def turret(name, spec):
    groups = {f"dtc:tier_{n}": turret_tier(spec, n) for n in TIERS}
    events = {
        f"dtc:tier_{n}": {
            "remove": {"component_groups": [g for g in groups if g != f"dtc:tier_{n}"]},
            "add": {"component_groups": [f"dtc:tier_{n}"]},
        }
        for n in TIERS
    }
    events["minecraft:entity_spawned"] = {"add": {"component_groups": ["dtc:tier_1"]}}
    events["dm:talk"] = {}
    return {
        "format_version": "1.26.50",
        "minecraft:entity": {
            "description": {"identifier": f"dm:{name}", "is_summonable": True, "is_spawnable": False},
            "component_groups": groups,
            "components": {
                "minecraft:type_family": {"family": ["dm_turret", "inanimate"]},
                "minecraft:health": {"value": MAX_TURRET_HEALTH, "max": MAX_TURRET_HEALTH},
                "minecraft:collision_box": {"width": 1.0, "height": 1.0},
                "minecraft:physics": {},
                "minecraft:knockback_resistance": {"value": 1.0},
                # Stands still: no speed, but ranged attacks expect movement parts.
                "minecraft:movement": {"value": 0},
                "minecraft:movement.basic": {},
                "minecraft:navigation.walk": {},
                "minecraft:persistent": {},
                "minecraft:nameable": {"always_show": False, "allow_name_tag_renaming": False},
                "minecraft:fire_immune": {},
                "minecraft:damage_sensor": {
                    "triggers": [
                        {"on_damage": {"filters": NO_PLAYER_DAMAGE}, "deals_damage": "no"},
                        {"deals_damage": "yes"},
                    ]
                },
                "minecraft:shooter": {"def": spec["shoots"]},
                # Talking opens its repair / upgrade menu (scripts/defenses.js).
                "minecraft:interact": {
                    "interactions": [
                        {
                            "on_interact": {
                                "filters": {"test": "is_family", "subject": "other", "value": "player"},
                                "event": "dm:talk",
                                "target": "self",
                            },
                            "interact_text": "action.interact.dtc_turret",
                        }
                    ]
                },
            },
            "events": events,
        },
    }


def label():
    """Floating text: an entity with no model whose name tag is always shown
    (shop names, the mall's leaderboards). Can't be hurt, pushed or moved."""
    return {
        "format_version": "1.26.50",
        "minecraft:entity": {
            "description": {"identifier": "dm:label", "is_summonable": True, "is_spawnable": False},
            "components": {
                "minecraft:type_family": {"family": ["dm_label", "inanimate"]},
                "minecraft:health": {"value": 1, "max": 1},
                "minecraft:collision_box": {"width": 0.1, "height": 0.1},
                "minecraft:physics": {"has_gravity": False, "has_collision": False},
                "minecraft:knockback_resistance": {"value": 1.0},
                "minecraft:persistent": {},
                "minecraft:fire_immune": {},
                "minecraft:nameable": {"always_show": True, "allow_name_tag_renaming": False},
                "minecraft:damage_sensor": {"triggers": [{"deals_damage": "no"}]},
            },
        },
    }


def label_client():
    """No render controllers: nothing is drawn but the name tag."""
    return {
        "format_version": "1.8.0",
        "minecraft:client_entity": {
            "description": {
                "identifier": "dm:label",
                "materials": {"default": "entity_alphatest"},
                "textures": {"default": "textures/entity/steve"},
                "geometry": {"default": "geometry.humanoid"},
                "render_controllers": [],
            }
        },
    }


def vendor():
    return {
        "format_version": "1.26.50",
        "minecraft:entity": {
            "description": {"identifier": "dm:vendor", "is_summonable": True, "is_spawnable": False},
            "components": {
                "minecraft:type_family": {"family": ["dm_vendor", "npc"]},
                "minecraft:health": {"value": 20, "max": 20},
                "minecraft:collision_box": {"width": 0.6, "height": 1.9},
                "minecraft:physics": {},
                "minecraft:knockback_resistance": {"value": 1.0},
                "minecraft:persistent": {},
                "minecraft:nameable": {"always_show": True, "allow_name_tag_renaming": False},
                "minecraft:damage_sensor": {"triggers": [{"deals_damage": "no"}]},
                "minecraft:behavior.look_at_player": {"priority": 1, "look_distance": 8},
                # Talking opens the shop (scripts/shop.js listens for the interaction).
                "minecraft:interact": {
                    "interactions": [
                        {
                            "on_interact": {
                                "filters": {"test": "is_family", "subject": "other", "value": "player"},
                                "event": "dm:talk",
                                "target": "self",
                            },
                            "interact_text": "action.interact.trade",
                        }
                    ]
                },
            },
            "events": {"dm:talk": {}},
        },
    }


def item(item_id, spec):
    return {
        "format_version": "1.26.50",
        "minecraft:item": {
            "description": {"identifier": f"dm:{item_id}", "menu_category": {"category": "equipment"}},
            "components": {
                "minecraft:icon": f"dm_{item_id}",
                "minecraft:display_name": {"value": spec["name"]},
                "minecraft:max_stack_size": 16,
                # Using it on a block places the defense (scripts/defenses.js
                # registers this component; a plain item has no use, so the
                # game never reports the interaction otherwise).
                "dtc:placer": {},
            },
        },
    }


def renamed_template(template, ident):
    data = json.loads((ROOT / f"tools/templates/{template}.entity.json").read_text(encoding="utf-8"))
    data["minecraft:client_entity"]["description"]["identifier"] = ident
    return data


def write_defenses():
    for name, spec in TURRETS.items():
        write(BP / f"{name}.json", turret(name, spec))
        write(RP / f"{name}.entity.json", renamed_template(spec["template"], f"dm:{name}"))
    write(BP / "vendor.json", vendor())
    write(BP / "label.json", label())
    write(RP / "label.entity.json", label_client())
    write(RP / "vendor.entity.json", renamed_template("wandering_trader", "dm:vendor"))
    items = ROOT / "packs/BP/items"
    items.mkdir(exist_ok=True)
    for item_id, spec in ITEMS.items():
        write(items / f"{item_id}.json", item(item_id, spec))
    textures = ROOT / "packs/RP/textures"
    textures.mkdir(exist_ok=True)
    write(
        textures / "item_texture.json",
        {
            "resource_pack_name": "defend_the_core",
            "texture_name": "atlas.items",
            "texture_data": {f"dm_{i}": {"textures": s["icon"]} for i, s in ITEMS.items()},
        },
    )


if __name__ == "__main__":
    main()
