"""Generate the attacker entity files from one roster.

    python tools/gen_entities.py

Writes packs/BP/entities/<name>.json and packs/RP/entity/<name>.entity.json
for every mob in ROSTER. The generated files are committed; edit this script,
not them. dm:core is hand-written.

Client entities use the plain 1.8/1.10 vanilla formats with the default
render controller. The 1.26 zombie client file (spear and kinetic weapon
queries) renders custom entities invisible.
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BP = ROOT / "packs/BP/entities"
RP = ROOT / "packs/RP/entity"
GEN_NOTE = "Generated by tools/gen_entities.py; edit that instead."

# ---------------------------------------------------------------- roster

ROSTER = {
    "zombie": {
        "base": "zombie", "name": "Siege Zombie", "health": 20, "speed": 0.23, "attack": 3,
        "texture": "textures/entity/zombie/zombie", "families": ["zombie", "undead"],
    },
    "swarmer": {
        "base": "zombie", "name": "Swarmer", "health": 14, "speed": 0.27, "attack": 2,
        "texture": "textures/entity/zombie/husk", "families": ["zombie", "undead"], "scale": 0.9,
    },
    "digger": {
        "base": "zombie", "name": "Digger", "health": 26, "speed": 0.21, "attack": 3,
        "texture": "textures/entity/zombie/zombie", "families": ["zombie", "undead"],
        "equipment": "loot_tables/dm/digger_gear.json",
    },
    "skeleton": {
        "base": "skeleton", "name": "Siege Skeleton", "health": 20, "speed": 0.25,
        "texture": "textures/entity/skeleton/skeleton", "families": ["skeleton", "undead"],
    },
    "siege_skeleton": {
        "base": "skeleton", "name": "Siege Archer", "health": 20, "speed": 0.25,
        "texture": "textures/entity/skeleton/stray", "families": ["skeleton", "undead"],
    },
    "sapper": {
        "base": "creeper", "name": "Sapper", "health": 20, "speed": 0.22,
        "families": ["creeper"], "power": 3, "template": "creeper",
    },
    # Flyers: no breach modules; they bypass walls and attack from the air.
    "ghast": {
        "base": "ghast", "name": "Siege Ghast", "health": 20, "speed": 0.06,
        "families": ["ghast"], "template": "ghast", "runtime": True, "targeting": "core_only",
    },
    "blaze": {
        "base": "blaze", "name": "Blaze", "health": 20, "speed": 0.23,
        "families": ["blaze"], "template": "blaze", "runtime": True,
    },
    "phantom": {
        "base": "phantom", "name": "Phantom", "health": 20, "speed": 1.8, "attack": 6,
        "families": ["phantom", "undead"], "template": "phantom",
    },
}
FLYERS = ("ghast", "blaze", "phantom")
# Walking parts of common_components() a flyer doesn't get.
WALKING = (
    "minecraft:navigation.walk", "minecraft:movement.basic", "minecraft:jump.static",
    "minecraft:can_climb", "minecraft:behavior.random_stroll", "minecraft:pushable_by_block",
)

# ---------------------------------------------------------------- behavior


def target_entry(family, max_dist, must_see, priority=None):
    entry = {
        "filters": {"test": "is_family", "subject": "other", "value": family},
        "max_dist": max_dist,
        "must_see": must_see,
    }
    if priority is not None:
        entry["priority"] = priority
    return entry


def targeting_groups(flyer=False):
    common = {"priority": 2, "must_see": False, "reselect_targets": True, "within_radius": 64}
    if flyer:
        # Flyers sit well above the core; without this they never pick it up.
        common["target_search_height"] = 80
    return {
        # Core only; ignores players unless hurt by one.
        "dm:tgt_core_only": {
            "minecraft:behavior.nearest_attackable_target": {
                **common, "entity_types": [target_entry("dm_core", 64, False)],
            }
        },
        # Core first, players inside the aggro radius second.
        "dm:tgt_prioritized": {
            "minecraft:behavior.nearest_prioritized_attackable_target": {
                **common,
                "entity_types": [
                    target_entry("dm_core", 64, False, 0),
                    target_entry("player", 6, True, 1),
                ],
            }
        },
        # Whichever valid target is nearest.
        "dm:tgt_nearest": {
            "minecraft:behavior.nearest_attackable_target": {
                **common,
                "entity_types": [target_entry("dm_core", 64, False), target_entry("player", 6, True)],
            }
        },
    }


def targeting_events():
    names = ["dm:tgt_core_only", "dm:tgt_prioritized", "dm:tgt_nearest"]
    return {
        name: {
            "remove": {"component_groups": [n for n in names if n != name]},
            "add": {"component_groups": [name]},
        }
        for name in names
    }


def common_components(mob):
    return {
        "minecraft:type_family": {"family": ["dm_attacker", *mob["families"], "monster", "mob"]},
        "minecraft:health": {"value": mob["health"], "max": mob["health"]},
        "minecraft:movement": {"value": mob["speed"]},
        "minecraft:follow_range": {"value": 64, "max": 64},
        "minecraft:collision_box": {"width": 0.6, "height": 1.9},
        # Retaliate against players, never against fellow attackers (stray
        # arrows otherwise start infighting).
        "minecraft:behavior.hurt_by_target": {
            "priority": 1,
            "entity_types": [{"filters": {
                "test": "is_family", "subject": "other", "operator": "!=", "value": "dm_attacker",
            }}],
        },
        "minecraft:behavior.random_stroll": {"priority": 7, "speed_multiplier": 1},
        "minecraft:behavior.look_at_player": {"priority": 8, "look_distance": 6},
        "minecraft:behavior.random_look_around": {"priority": 9},
        "minecraft:breathable": {
            "total_supply": 15, "suffocate_time": 0, "breathes_air": True, "breathes_water": True,
        },
        "minecraft:can_climb": {},
        "minecraft:jump.static": {},
        "minecraft:movement.basic": {},
        "minecraft:navigation.walk": {"can_walk": True, "is_amphibious": True, "can_pass_doors": True},
        "minecraft:physics": {},
        "minecraft:pushable_by_entity": {},
        "minecraft:pushable_by_block": {},
        "minecraft:nameable": {},
        "minecraft:persistent": {},
        "minecraft:conditional_bandwidth_optimization": {},
        "minecraft:hurt_on_condition": {"damage_conditions": [
            {"cause": "lava", "damage_per_tick": 4, "filters": {"test": "in_lava"}},
        ]},
    }


def behavior(name, mob):
    components = common_components(mob)
    groups = targeting_groups(flyer=mob["base"] in FLYERS)
    default = mob.get("targeting", "prioritized")
    events = {"minecraft:entity_spawned": {"add": {"component_groups": [f"dm:tgt_{default}"]}}}
    events.update(targeting_events())

    if mob["base"] == "zombie":
        components["minecraft:attack"] = {"damage": mob["attack"]}
        components["minecraft:behavior.melee_box_attack"] = {"priority": 4, "track_target": True}
    elif mob["base"] == "skeleton":
        components["minecraft:equipment"] = {"table": "loot_tables/entities/skeleton_gear.json"}
        components["minecraft:shooter"] = {"def": "minecraft:arrow", "sound": "bow"}
        components["minecraft:behavior.ranged_attack"] = {
            "priority": 0,
            "attack_interval": {"min": 3.0, "max": 3.0},
            "attack_range": {"min": 0.0, "max": 15.0},
        }
        components["minecraft:navigation.walk"]["avoid_water"] = True
    elif mob["base"] in FLYERS:
        for key in WALKING:
            components.pop(key, None)
        components["minecraft:can_fly"] = {}
        components["minecraft:fire_immune"] = {}
        flight = {
            # Floats slowly and shells the core from up to 64 blocks; its
            # fireballs explode and break blocks.
            "ghast": {
                "minecraft:collision_box": {"width": 4.0, "height": 4.0},
                "minecraft:physics": {},
                "minecraft:navigation.float": {"can_path_over_water": True},
                "minecraft:behavior.float": {"priority": 0},
                "minecraft:behavior.float_wander": {
                    # Vanilla wander drifts upward until the ghast is too high to
                    # fire at the core (tested); keep it low and close.
                    "priority": 3, "must_reach": True, "random_reselect": True, "float_duration": {"min": 2, "max": 7},
                    "xz_dist": 8, "y_dist": 3, "y_offset": -2,
                },
                "minecraft:behavior.ranged_attack": {
                    "priority": 1, "attack_range": {"min": 0.0, "max": 64.0},
                    "charge_charged_trigger": 1, "charge_shoot_trigger": 2,
                },
                "minecraft:shooter": {"def": "minecraft:fireball"},
            },
            # Fires bursts of small fireballs, which set wooden defenses
            # alight. Its flight comes from the vanilla blaze runtime, which
            # walks on vanilla's components, so it keeps them.
            "blaze": {
                "minecraft:collision_box": {"width": 0.5, "height": 1.8},
                "minecraft:physics": {},
                "minecraft:movement.basic": {},
                "minecraft:jump.static": {},
                "minecraft:navigation.walk": {"avoid_damage_blocks": True, "avoid_water": True, "can_path_over_water": True},
                "minecraft:behavior.float": {"priority": 0},
                "minecraft:behavior.ranged_attack": {
                    "priority": 3, "attack_interval": {"min": 3.0, "max": 5.0}, "attack_range": {"min": 0.0, "max": 48.0},
                    "charge_shoot_trigger": 4.0, "burst_shots": 3, "burst_interval": 0.3,
                },
                "minecraft:shooter": {"def": "minecraft:small_fireball"},
            },
            # Circles high above and swoops down on its target.
            "phantom": {
                "minecraft:collision_box": {"width": 0.9, "height": 0.5},
                "minecraft:physics": {"has_gravity": False},
                "minecraft:movement.glide": {"start_speed": 0.1, "speed_when_turning": 0.2},
                "minecraft:attack": {"damage": mob.get("attack", 6)},
                "minecraft:behavior.swoop_attack": {"priority": 2},
                "minecraft:behavior.circle_around_anchor": {
                    "priority": 3, "goal_radius": 1, "height_offset_range": {"min": -4, "max": 5},
                    "height_above_target_range": {"min": 10, "max": 20},
                },
            },
        }[mob["base"]]
        components.update(flight)
        if mob["base"] == "blaze":
            components.pop("minecraft:can_fly", None)
    elif mob["base"] == "creeper":
        components["minecraft:collision_box"] = {"width": 0.6, "height": 1.8}
        components["minecraft:attack"] = {"damage": 3}
        components["minecraft:behavior.melee_box_attack"] = {"priority": 4, "track_target": True}
        components["minecraft:behavior.swell"] = {"priority": 2, "start_distance": 2.5, "stop_distance": 6}
        components["minecraft:target_nearby_sensor"] = {
            "inside_range": 2.5,
            "outside_range": 6,
            "must_see": True,
            "on_inside_range": {"event": "minecraft:start_exploding", "target": "self"},
            "on_outside_range": {"event": "minecraft:stop_exploding", "target": "self"},
            "on_vision_lost_inside_range": {"event": "minecraft:stop_exploding", "target": "self"},
        }
        explode = {"fuse_length": 1.5, "fuse_lit": True, "power": mob["power"],
                   "causes_fire": False, "breaks_blocks": True, "destroy_affected_by_griefing": False}
        groups["dm:exploding"] = {"minecraft:explode": explode}
        # Scripts fire this when the sapper is stuck at a wall (detonate_stuck).
        groups["dm:detonating"] = {"minecraft:explode": explode}
        events["minecraft:start_exploding"] = {"add": {"component_groups": ["dm:exploding"]}}
        events["minecraft:stop_exploding"] = {"remove": {"component_groups": ["dm:exploding"]}}
        events["dm:detonate"] = {"add": {"component_groups": ["dm:detonating"]}}

    if mob.get("equipment"):
        components["minecraft:equipment"] = {
            "table": mob["equipment"],
            "slot_drop_chance": [
                {"slot": "slot.weapon.mainhand", "drop_chance": 0},
                {"slot": "slot.armor.head", "drop_chance": 0},
            ],
        }
    if mob.get("scale"):
        components["minecraft:scale"] = {"value": mob["scale"]}

    return {
        "format_version": "1.26.50",
        "minecraft:entity": {
            "description": {
                "identifier": f"dm:{name}",
                "is_summonable": True,
                "is_spawnable": True,
                **({"runtime_identifier": f"minecraft:{mob['base']}"} if mob.get("runtime") else {}),
            },
            "components": components,
            "component_groups": groups,
            "events": events,
        },
    }


# ---------------------------------------------------------------- client

HUMANOID_SCRIPTS = {
    "pre_animation": [
        "variable.tcos0 = (Math.cos(query.modified_distance_moved * 38.17) * query.modified_move_speed / variable.gliding_speed_value) * 57.3;",
    ],
}

HUMANOID_ANIMATIONS = {
    "look_at_target_default": "animation.humanoid.look_at_target.default",
    "look_at_target_gliding": "animation.humanoid.look_at_target.gliding",
    "look_at_target_swimming": "animation.humanoid.look_at_target.swimming",
    "move": "animation.humanoid.move",
    "riding.arms": "animation.humanoid.riding.arms",
    "riding.legs": "animation.humanoid.riding.legs",
    "riding.body": "animation.humanoid.riding.body",
    "holding": "animation.humanoid.holding",
    "attack.rotations": "animation.humanoid.attack.rotations",
    "bob": "animation.humanoid.bob",
}
HUMANOID_CONTROLLERS = [
    {"look_at_target": "controller.animation.humanoid.look_at_target"},
    {"move": "controller.animation.humanoid.move"},
    {"riding": "controller.animation.humanoid.riding"},
    {"holding": "controller.animation.humanoid.holding"},
    {"attack": "controller.animation.humanoid.attack"},
    {"bob": "controller.animation.humanoid.bob"},
]


def client(name, mob):
    ident = f"dm:{name}"
    if mob.get("template"):
        # A Mojang client entity in the 1.8/1.10 format, renamed (tools/templates).
        data = json.loads((ROOT / f"tools/templates/{mob['template']}.entity.json").read_text(encoding="utf-8"))
        data["minecraft:client_entity"]["description"]["identifier"] = ident
        return data

    animations = dict(HUMANOID_ANIMATIONS)
    controllers = list(HUMANOID_CONTROLLERS)
    if mob["base"] == "zombie":
        geometry, material = "geometry.zombie.v1.8", "zombie"
        animations["zombie_attack_bare_hand"] = "animation.zombie.attack_bare_hand"
        controllers.append({"zombie_attack_bare_hand": "controller.animation.zombie.attack_bare_hand"})
        egg = "spawn_egg_zombie"
    else:
        geometry, material = "geometry.skeleton.v1.8", "skeleton"
        animations["bow_and_arrow"] = "animation.humanoid.bow_and_arrow"
        animations["skeleton_attack"] = "animation.skeleton.attack"
        controllers.append({"bow_and_arrow": "controller.animation.humanoid.bow_and_arrow"})
        controllers.append({"skeleton_attack": "controller.animation.skeleton.attack"})
        egg = "spawn_egg_skeleton"
    return {
        "format_version": "1.8.0",
        "minecraft:client_entity": {"description": {
            "identifier": ident,
            "min_engine_version": "1.8.0",
            "materials": {"default": material},
            "textures": {"default": mob["texture"]},
            "geometry": {"default": geometry},
            "scripts": HUMANOID_SCRIPTS,
            "animations": animations,
            "animation_controllers": controllers,
            "render_controllers": ["controller.render.default"],
            "enable_attachables": True,
            "spawn_egg": {"texture": egg},
        }},
    }


# ---------------------------------------------------------------- write


def write(path, data):
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def main():
    for name, mob in ROSTER.items():
        write(BP / f"{name}.json", behavior(name, mob))
        write(RP / f"{name}.entity.json", client(name, mob))
    lang = ROOT / "packs/RP/texts/en_US.lang"
    lines = [
        "pack.name=Defend the Core Resources",
        "pack.description=Client entities for Defend the Core",
        "entity.dm:core.name=Core",
    ]
    for name, mob in ROSTER.items():
        lines.append(f"entity.dm:{name}.name={mob['name']}")
        lines.append(f"item.spawn_egg.entity.dm:{name}.name=Spawn {mob['name']}")
    lang.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {len(ROSTER)} mobs; {GEN_NOTE}")


if __name__ == "__main__":
    main()
